package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/swagger" // Note: v2 uses this path usually
	"github.com/shyamsundaar/karino-mock-server/controllers"
	"github.com/shyamsundaar/karino-mock-server/initializers"
	"github.com/shyamsundaar/karino-mock-server/middleware"

	// IMPORTANT: Replace this with your actual docs path generated by 'swag init'
	_ "github.com/shyamsundaar/karino-mock-server/docs"
)

// @title ERP Farmer & Sales Order Integration API
// @version 1.0
// @description This is a sample CRUD API for managing Notes and Farmer Details
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email support@example.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name APIKey

// @security ApiKeyAuth
// @host localhost:8001
// @BasePath /
func main() {
	app := fiber.New()
	micro := fiber.New()
	// Middleware
	app.Use(logger.New())
	app.Use(cors.New(cors.Config{
		AllowOrigins: "*",
		AllowHeaders: "Origin, Content-Type, Accept, Authorization, APIKey",
		AllowMethods: "GET,POST,PUT,PATCH,DELETE,OPTIONS",
	}))

	// Swagger Route (Accessible at http://localhost:8001/swagger/index.html)
	app.Get("/swagger/*", swagger.HandlerDefault)

	// Mount API routes
	app.Mount("/", micro)

	// --- Details Routes ---
	micro.Route("/spic_to_erp", func(router fiber.Router) {
		router.Use(middleware.ApiKeyAuth)
		router.Use(middleware.JSONProviderMiddleware)
		router.Route("/customers", func(router fiber.Router) {
			router.Post("/:coopId/farmers", controllers.CreateCustomerDetailHandler)
			router.Get("/:coopId/farmers", controllers.FindCustomerDetailsHandler)
			router.Get("/:coopId/farmers/:farmerId", controllers.GetCustomerDetailHandler)

			router.Post("/:coopId/salesorders", controllers.CreateCustomerSalesOrderHandler)
			router.Get("/:coopId/salesorders", controllers.GetCustomerSalesDetailHandler)
			router.Get("/:coopId/salesorders/:orderId", controllers.GetCustomerSalesOrderDetailsHandler)
			
			router.Post("/:coopId/salesorders/deliverydocuments", controllers.CreateCustomerDeliveryDocumentDetailsHandler)
			router.Get("/:coopId/salesorders/deliverydocuments", controllers.GetCustomerDeliveryDocumentDetailHandler)
			router.Get("/:coopId/salesorders/:orderId/deliverydocuments", controllers.GetDeliveryDetailParticularHandler)
		})

		router.Route("/vendors", func(router fiber.Router) {
			router.Post("/:coopId/farmers", controllers.CreateVendorDetailHandler)
			router.Get("/:coopId/farmers", controllers.FindVendorDetailsHandler)
			router.Get("/:coopId/farmers/:farmerId", controllers.GetVendorDetailHandler)

		})
	})

	log.Fatal(app.Listen(":8001"))
}

func init() {

	config, err := initializers.LoadConfig(".")
	if err != nil {
		log.Fatalln("Failed to load environment variables! \n", err.Error())
	}
	initializers.ConnectDB(&config)
}
